import {
  OSMD_PREVIEW_ZOOM_DEBOUNCE_MS,
} from './osmdPreviewConstants'

export const DEFAULT_NATIVE_PREVIEW_ZOOM_PERCENT = 66
export const NATIVE_PREVIEW_MIN_ZOOM_PERCENT = 35
export const NATIVE_PREVIEW_MAX_ZOOM_PERCENT = 160
export const NATIVE_PREVIEW_ZOOM_DEBOUNCE_MS = OSMD_PREVIEW_ZOOM_DEBOUNCE_MS
export const DEFAULT_NATIVE_PREVIEW_PAPER_SCALE_PERCENT = 100
export const DEFAULT_NATIVE_PREVIEW_HORIZONTAL_MARGIN_PX = 68
export const DEFAULT_NATIVE_PREVIEW_FIRST_PAGE_TOP_MARGIN_PX = 132
export const DEFAULT_NATIVE_PREVIEW_FOLLOWING_PAGE_TOP_MARGIN_PX = 10
export const DEFAULT_NATIVE_PREVIEW_BOTTOM_MARGIN_PX = 86
export const DEFAULT_NATIVE_PREVIEW_SHOW_PAGE_NUMBERS = true
export const DEFAULT_NATIVE_PREVIEW_MIN_EIGHTH_GAP_PX = 20
export const DEFAULT_NATIVE_PREVIEW_MIN_GRAND_STAFF_GAP_PX = 44
