import { useEffect } from 'react'
import { handleKeyboardCommandEvent } from './handleKeyboardCommandEvent'
import type { KeyboardCommandEffectParams } from './keyboardCommandTypes'

export function useKeyboardCommandEffect(params: KeyboardCommandEffectParams): void {
  const {
    isAnyPreviewOpen,
    draggingSelection,
    isSelectionVisible,
    measurePairs,
    activeSelection,
    selectedSelections,
    selectedMeasureScope,
    activeTieSelection,
    activeAccidentalSelection,
    activePedalSelection,
    pedalSpans,
    measureKeyFifthsFromImport,
    noteClipboardRef,
    importedNoteLookupRef,
    measureKeyFifthsFromImportRef,
    measureTimeSignaturesFromImportRef,
    measurePairsFromImportRef,
    scoreScrollRef,
    undoLastScoreEdit,
    handleMoveSelectionsByKeyboardSteps,
    handleMoveSelectionByKeyboardArrow,
    pushUndoSnapshot,
    applyKeyboardEditResult,
    playAccidentalEditPreview,
    setPedalSpans,
    setActiveTieSelection,
    setActiveAccidentalSelection,
    setActivePedalSelection,
    setIsSelectionVisible,
    setSelectedSelections,
    setSelectedMeasureScope,
    setNotationPaletteLastAction,
  } = params

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      handleKeyboardCommandEvent({
        event,
        isAnyPreviewOpen,
        draggingSelection,
        isSelectionVisible,
        measurePairs,
        activeSelection,
        selectedSelections,
        selectedMeasureScope,
        activeTieSelection,
        activeAccidentalSelection,
        activePedalSelection,
        pedalSpans,
        measureKeyFifthsFromImport,
        noteClipboardRef,
        importedNoteLookupRef,
        measureKeyFifthsFromImportRef,
        measureTimeSignaturesFromImportRef,
        measurePairsFromImportRef,
        scoreScrollRef,
        undoLastScoreEdit,
        handleMoveSelectionsByKeyboardSteps,
        handleMoveSelectionByKeyboardArrow,
        pushUndoSnapshot,
        applyKeyboardEditResult,
        playAccidentalEditPreview,
        setPedalSpans,
        setActiveTieSelection,
        setActiveAccidentalSelection,
        setActivePedalSelection,
        setIsSelectionVisible,
        setSelectedSelections,
        setSelectedMeasureScope,
        setNotationPaletteLastAction,
      })
    }

    window.addEventListener('keydown', onKeyDown)
    return () => {
      window.removeEventListener('keydown', onKeyDown)
    }
  }, [
    activeAccidentalSelection,
    activeSelection,
    activeTieSelection,
    activePedalSelection,
    applyKeyboardEditResult,
    draggingSelection,
    handleMoveSelectionByKeyboardArrow,
    handleMoveSelectionsByKeyboardSteps,
    importedNoteLookupRef,
    isAnyPreviewOpen,
    isSelectionVisible,
    measureKeyFifthsFromImport,
    measureKeyFifthsFromImportRef,
    measurePairs,
    pedalSpans,
    measurePairsFromImportRef,
    measureTimeSignaturesFromImportRef,
    noteClipboardRef,
    playAccidentalEditPreview,
    pushUndoSnapshot,
    scoreScrollRef,
    setActivePedalSelection,
    selectedMeasureScope,
    selectedSelections,
    setActiveAccidentalSelection,
    setActiveTieSelection,
    setIsSelectionVisible,
    setNotationPaletteLastAction,
    setPedalSpans,
    setSelectedMeasureScope,
    setSelectedSelections,
    undoLastScoreEdit,
  ])
}
