import { useMemo } from 'react'
import { toDisplayDuration } from '../layout/demand'
import type { ScoreBoardProps, ScoreViewAdapterParams } from './scoreViewAdapterTypes'

export function useScoreBoardProps(params: ScoreViewAdapterParams): ScoreBoardProps {
  const { appState, editorRefs, layout, chordMarker, workspace, editorUi, playback } = params

  return useMemo<ScoreBoardProps>(() => ({
    scoreScrollRef: editorRefs.scoreScrollRef,
    scoreStageRef: editorRefs.scoreStageRef,
    playheadRef: playback.playheadElementRef,
    displayScoreWidth: layout.displayScoreWidth,
    displayScoreHeight: layout.displayScoreHeight,
    chordMarkerStyleMetrics: layout.chordMarkerStyleMetrics,
    scoreSurfaceLogicalWidthPx: layout.scoreWidth,
    scoreSurfaceLogicalHeightPx: layout.scoreHeight,
    scoreScaleX: layout.scoreScaleX,
    scoreScaleY: layout.scoreScaleY,
    scoreSurfaceOffsetXPx: layout.scoreSurfaceOffsetXPx,
    scoreSurfaceOffsetYPx: layout.scoreSurfaceOffsetYPx,
    measureRulerTicks: chordMarker.measureRulerTicks,
    chordRulerMarkers: chordMarker.chordRulerMarkers,
    onChordRulerMarkerClick: chordMarker.onChordRulerMarkerClick,
    playheadRectPx: playback.playheadRectPx,
    playheadStatus: playback.playheadStatus,
    selectedMeasureHighlightRectPx: chordMarker.selectedMeasureHighlightRectPx,
    draggingSelection: appState.draggingSelection,
    scoreRef: editorRefs.scoreRef,
    scoreOverlayRef: editorRefs.scoreOverlayRef,
    onBeginDrag: playback.onBeginDragWithFirstMeasureDebug,
    onSurfacePointerMove: workspace.onSurfacePointerMove,
    onEndDrag: playback.onEndDragWithFirstMeasureDebug,
    selectedStaffLabel: appState.activeSelection.staff === 'treble' ? '高音谱表' : '低音谱表',
    selectedPitchLabel: editorUi.currentSelectionPitchLabel,
    selectedDurationLabel: toDisplayDuration(editorUi.currentSelection.duration),
    selectedPosition: editorUi.currentSelectionPosition,
    selectedPoolSize: editorUi.selectedPoolSize,
    trebleSequenceText: editorUi.trebleSequenceText,
    bassSequenceText: editorUi.bassSequenceText,
    playheadDebugLogText: playback.playheadDebugLogText,
  }), [
    appState.activeSelection.staff,
    appState.draggingSelection,
    chordMarker.chordRulerMarkers,
    chordMarker.measureRulerTicks,
    chordMarker.onChordRulerMarkerClick,
    chordMarker.selectedMeasureHighlightRectPx,
    editorRefs.scoreOverlayRef,
    editorRefs.scoreRef,
    editorRefs.scoreScrollRef,
    editorRefs.scoreStageRef,
    editorUi.bassSequenceText,
    editorUi.currentSelection.duration,
    editorUi.currentSelectionPitchLabel,
    editorUi.currentSelectionPosition,
    editorUi.selectedPoolSize,
    editorUi.trebleSequenceText,
    layout.chordMarkerStyleMetrics,
    layout.displayScoreHeight,
    layout.displayScoreWidth,
    layout.scoreHeight,
    layout.scoreScaleX,
    layout.scoreScaleY,
    layout.scoreSurfaceOffsetXPx,
    layout.scoreSurfaceOffsetYPx,
    layout.scoreWidth,
    playback.onBeginDragWithFirstMeasureDebug,
    playback.onEndDragWithFirstMeasureDebug,
    playback.playheadDebugLogText,
    playback.playheadElementRef,
    playback.playheadRectPx,
    playback.playheadStatus,
    workspace.onSurfacePointerMove,
  ])
}
