import { useScoreAudioPreviewController } from './useScoreAudioPreviewController'
import { useScoreEditorUiController } from './useScoreEditorUiController'
import { useScoreAppState } from './useScoreAppState'
import { useScoreEditorRefs } from './useScoreEditorRefs'
import { useHorizontalScoreLayout } from './useHorizontalScoreLayout'
import { useScoreCoreEditingController } from './useScoreCoreEditingController'
import type { ScoreNote } from '../types'

export function useScoreEditorUiRuntime(params: {
  appState: ReturnType<typeof useScoreAppState>
  editorRefs: ReturnType<typeof useScoreEditorRefs>
  layout: ReturnType<typeof useHorizontalScoreLayout>
  coreEditing: ReturnType<typeof useScoreCoreEditingController>
  audioPreview: ReturnType<typeof useScoreAudioPreviewController>
  initialTrebleNotes: ScoreNote[]
  isWorkspaceBlocked?: boolean
}) {
  const { appState, editorRefs, layout, coreEditing, audioPreview, initialTrebleNotes, isWorkspaceBlocked = false } = params

  return useScoreEditorUiController({
    notes: appState.notes,
    bassNotes: appState.bassNotes,
    importFeedback: appState.importFeedback,
    selectionController: {
      notes: appState.notes,
      bassNotes: appState.bassNotes,
      measurePairs: layout.measurePairs,
      pedalSpans: appState.pedalSpans,
      activeSelection: appState.activeSelection,
      selectedSelections: appState.selectedSelections,
      selectedMeasureScope: appState.selectedMeasureScope,
      activeTieSelection: appState.activeTieSelection,
      activePedalSelection: appState.activePedalSelection,
      isSelectionVisible: appState.isSelectionVisible,
      draggingSelection: appState.draggingSelection,
      selectionFrameIntent: appState.selectionFrameIntent,
      importFeedback: appState.importFeedback,
      fallbackSelectionNote: initialTrebleNotes[0],
      trebleNoteById: layout.trebleNoteById,
      bassNoteById: layout.bassNoteById,
      trebleNoteIndexById: layout.trebleNoteIndexById,
      bassNoteIndexById: layout.bassNoteIndexById,
      importedNoteLookupRef: editorRefs.importedNoteLookupRef,
      activeSelectionRef: editorRefs.activeSelectionRef,
      activePedalSelectionRef: editorRefs.activePedalSelectionRef,
      pedalSpansRef: editorRefs.pedalSpansRef,
      selectedSelectionsRef: editorRefs.selectedSelectionsRef,
      fullMeasureRestCollapseScopeKeys: appState.fullMeasureRestCollapseScopeKeys,
      fullMeasureRestCollapseScopeKeysRef: editorRefs.fullMeasureRestCollapseScopeKeysRef,
      isSelectionVisibleRef: editorRefs.isSelectionVisibleRef,
      draggingSelectionRef: editorRefs.draggingSelectionRef,
      importFeedbackRef: editorRefs.importFeedbackRef,
      setIsSelectionVisible: appState.setIsSelectionVisible,
      setActiveSelection: appState.setActiveSelection,
      setSelectedSelections: appState.setSelectedSelections,
      setSelectedMeasureScope: appState.setSelectedMeasureScope,
      setActiveTieSelection: appState.setActiveTieSelection,
      setActivePedalSelection: appState.setActivePedalSelection,
      setSelectionFrameIntent: appState.setSelectionFrameIntent,
    },
    editorPreferencePersistence: {
      playheadFollowEnabled: appState.playheadFollowEnabled,
      showChordDegreeEnabled: appState.showChordDegreeEnabled,
      showChordMarkerBackgroundEnabled: appState.showChordMarkerBackgroundEnabled,
      staffInterGapPx: appState.staffInterGapPx,
      playbackTrebleVolumePercent: appState.playbackTrebleVolumePercent,
      playbackBassVolumePercent: appState.playbackBassVolumePercent,
      showInScoreMeasureNumbers: appState.showInScoreMeasureNumbers,
      setShowInScoreMeasureNumbers: appState.setShowInScoreMeasureNumbers,
      showNoteHeadJianpuEnabled: appState.showNoteHeadJianpuEnabled,
      setShowNoteHeadJianpuEnabled: appState.setShowNoteHeadJianpuEnabled,
    },
    midiInputController: {
      onMidiNoteNumber: coreEditing.mutation.applyMidiReplacementByNoteNumber,
    },
    osmdPreviewController: {
      measurePairs: layout.measurePairs,
      pedalSpans: appState.pedalSpans,
      measurePairsRef: editorRefs.measurePairsRef,
      measureKeyFifthsFromImportRef: editorRefs.measureKeyFifthsFromImportRef,
      measureDivisionsFromImportRef: editorRefs.measureDivisionsFromImportRef,
      measureTimeSignaturesFromImportRef: editorRefs.measureTimeSignaturesFromImportRef,
      musicXmlMetadataFromImportRef: editorRefs.musicXmlMetadataFromImportRef,
      importedNoteLookupRef: editorRefs.importedNoteLookupRef,
      horizontalMeasureFramesByPair: layout.horizontalMeasureFramesByPair,
      noteLayoutsByPairRef: editorRefs.noteLayoutsByPairRef,
      noteLayoutByKeyRef: editorRefs.noteLayoutByKeyRef,
      horizontalRenderOffsetXRef: editorRefs.horizontalRenderOffsetXRef,
      scoreScrollRef: editorRefs.scoreScrollRef,
      scoreScaleX: layout.scoreScaleX,
      setIsSelectionVisible: appState.setIsSelectionVisible,
      setActiveSelection: appState.setActiveSelection,
      setSelectedSelections: appState.setSelectedSelections,
      setDraggingSelection: appState.setDraggingSelection,
      setSelectedMeasureScope: appState.setSelectedMeasureScope,
      setSelectionFrameIntent: appState.setSelectionFrameIntent,
      clearActiveChordSelection: coreEditing.chordMarker.clearActiveChordSelection,
      resetMidiStepChain: coreEditing.sessionHelpers.resetMidiStepChain,
    },
    nativePreviewController: {
      measurePairs: layout.measurePairs,
      pedalSpans: appState.pedalSpans,
      chordRulerEntriesByPair: layout.chordRulerEntriesByPair,
      measureKeyFifthsFromImport: appState.measureKeyFifthsFromImport,
      measureTimeSignaturesFromImport: appState.measureTimeSignaturesFromImport,
      musicXmlMetadataFromImport: appState.musicXmlMetadataFromImport,
      supplementalSpacingTicksByPair: layout.supplementalSpacingTicksByPair,
      timeAxisSpacingConfig: appState.timeAxisSpacingConfig,
      grandStaffLayoutMetrics: layout.grandStaffLayoutMetrics,
      showInScoreMeasureNumbers: appState.showInScoreMeasureNumbers,
      showNoteHeadJianpuEnabled: appState.showNoteHeadJianpuEnabled,
      widthProbeRendererRef: editorRefs.widthProbeRendererRef,
    },
    isWorkspaceBlocked,
    isOsmdPreviewOpenRef: editorRefs.isOsmdPreviewOpenRef,
    isAnyPreviewOpenRef: editorRefs.isAnyPreviewOpenRef,
    notationPaletteController: {
      activeSelection: appState.activeSelection,
      selectedSelections: appState.selectedSelections,
      isSelectionVisible: appState.isSelectionVisible,
      measurePairsRef: editorRefs.measurePairsRef,
      measurePairsFromImportRef: editorRefs.measurePairsFromImportRef,
      importedNoteLookupRef: editorRefs.importedNoteLookupRef,
      measureKeyFifthsFromImportRef: editorRefs.measureKeyFifthsFromImportRef,
      measureTimeSignaturesFromImportRef: editorRefs.measureTimeSignaturesFromImportRef,
      setImportFeedback: appState.setImportFeedback,
      setIsNotationPaletteOpen: appState.setIsNotationPaletteOpen,
      setNotationPaletteSelection: appState.setNotationPaletteSelection,
      setNotationPaletteLastAction: appState.setNotationPaletteLastAction,
      applyKeyboardEditResult: coreEditing.mutation.applyKeyboardEditResult,
      playAccidentalEditPreview: audioPreview.playAccidentalEditPreview,
    },
    keyboardCommandController: {
      draggingSelection: appState.draggingSelection,
      isSelectionVisible: appState.isSelectionVisible,
      measurePairs: layout.measurePairs,
      activeSelection: appState.activeSelection,
      selectedSelections: appState.selectedSelections,
      selectedMeasureScope: appState.selectedMeasureScope,
      activeTieSelection: appState.activeTieSelection,
      activeAccidentalSelection: appState.activeAccidentalSelection,
      activePedalSelection: appState.activePedalSelection,
      pedalSpans: appState.pedalSpans,
      measureKeyFifthsFromImport: appState.measureKeyFifthsFromImport,
      activeSelectionRef: editorRefs.activeSelectionRef,
      measurePairsRef: editorRefs.measurePairsRef,
      measurePairsFromImportRef: editorRefs.measurePairsFromImportRef,
      importedNoteLookupRef: editorRefs.importedNoteLookupRef,
      measureLayoutsRef: editorRefs.measureLayoutsRef,
      measureKeyFifthsFromImportRef: editorRefs.measureKeyFifthsFromImportRef,
      measureTimeSignaturesFromImportRef: editorRefs.measureTimeSignaturesFromImportRef,
      scoreScrollRef: editorRefs.scoreScrollRef,
      layoutReflowHintRef: editorRefs.layoutReflowHintRef,
      layoutStabilityKey: layout.layoutStabilityKey,
      pushUndoSnapshot: coreEditing.mutation.pushUndoSnapshot,
      resetMidiStepChain: coreEditing.sessionHelpers.resetMidiStepChain,
      undoLastScoreEdit: coreEditing.mutation.undoLastScoreEdit,
      applyKeyboardEditResult: coreEditing.mutation.applyKeyboardEditResult,
      playAccidentalEditPreview: audioPreview.playAccidentalEditPreview,
      setPedalSpans: appState.setPedalSpans,
      setNotes: appState.setNotes,
      setBassNotes: appState.setBassNotes,
      setMeasurePairsFromImport: appState.setMeasurePairsFromImport,
      setIsSelectionVisible: appState.setIsSelectionVisible,
      setSelectedSelections: appState.setSelectedSelections,
      setSelectedMeasureScope: appState.setSelectedMeasureScope,
      setActiveSelection: appState.setActiveSelection,
      setSelectionFrameIntent: appState.setSelectionFrameIntent,
      setActiveTieSelection: appState.setActiveTieSelection,
      setActiveAccidentalSelection: appState.setActiveAccidentalSelection,
      setActivePedalSelection: appState.setActivePedalSelection,
      setNotationPaletteLastAction: appState.setNotationPaletteLastAction,
    },
  })
}
