import { useMemo } from 'react'
import { clampCanvasHeightPercent, clampScalePercent } from '../scorePresentation'
import { buildSpacingConfigControlHandlers } from './buildSpacingConfigControlHandlers'
import type { ScoreControlsProps, ScoreViewAdapterParams } from './scoreViewAdapterTypes'

export function useScoreControlsProps(params: ScoreViewAdapterParams): ScoreControlsProps {
  const { appState, editorRefs, layout, workspace, editorUi, playback } = params
  const spacingConfigHandlers = useMemo(
    () => buildSpacingConfigControlHandlers({ appState }),
    [
      appState.setChordMarkerPaddingPx,
      appState.setChordMarkerUiScalePercent,
      appState.setPageHorizontalPaddingPx,
      appState.setStaffInterGapPx,
      appState.setTimeAxisSpacingConfig,
    ],
  )

  return useMemo<ScoreControlsProps>(() => ({
    isPlaying: appState.isPlaying,
    onPlayScore: workspace.playScore,
    onStopScore: playback.stopActivePlaybackSession,
    onReset: workspace.resetScoreWithCollapseReset,
    playheadFollowEnabled: appState.playheadFollowEnabled,
    onTogglePlayheadFollow: () => appState.setPlayheadFollowEnabled((enabled) => !enabled),
    showChordDegreeEnabled: appState.showChordDegreeEnabled,
    onToggleChordDegreeDisplay: () => appState.setShowChordDegreeEnabled((enabled) => !enabled),
    showChordMarkerBackgroundEnabled: appState.showChordMarkerBackgroundEnabled,
    onToggleChordMarkerBackgroundDisplay: () => appState.setShowChordMarkerBackgroundEnabled((enabled) => !enabled),
    staffInterGapPx: appState.staffInterGapPx,
    showInScoreMeasureNumbers: appState.showInScoreMeasureNumbers,
    onToggleInScoreMeasureNumbers: () => appState.setShowInScoreMeasureNumbers((current) => !current),
    showNoteHeadJianpuEnabled: appState.showNoteHeadJianpuEnabled,
    onToggleNoteHeadJianpuDisplay: () => appState.setShowNoteHeadJianpuEnabled((current) => !current),
    autoScaleEnabled: appState.autoScaleEnabled,
    autoScalePercent: layout.autoScalePercent,
    onToggleAutoScale: () => appState.setAutoScaleEnabled((enabled) => !enabled),
    manualScalePercent: layout.safeManualScalePercent,
    onManualScalePercentChange: (nextPercent: number) =>
      appState.setManualScalePercent(clampScalePercent(nextPercent)),
    canvasHeightPercent: layout.safeCanvasHeightPercent,
    onCanvasHeightPercentChange: (nextPercent: number) =>
      appState.setCanvasHeightPercent(clampCanvasHeightPercent(nextPercent)),
    pageHorizontalPaddingPx: appState.pageHorizontalPaddingPx,
    chordMarkerUiScalePercent: layout.safeChordMarkerUiScalePercent,
    chordMarkerPaddingPx: layout.safeChordMarkerPaddingPx,
    baseMinGap32Px: appState.timeAxisSpacingConfig.baseMinGap32Px,
    leadingBarlineGapPx: appState.timeAxisSpacingConfig.leadingBarlineGapPx,
    secondChordSafeGapPx: appState.timeAxisSpacingConfig.secondChordSafeGapPx,
    durationGapRatio32: appState.timeAxisSpacingConfig.durationGapRatios.thirtySecond,
    durationGapRatio16: appState.timeAxisSpacingConfig.durationGapRatios.sixteenth,
    durationGapRatio8: appState.timeAxisSpacingConfig.durationGapRatios.eighth,
    durationGapRatio4: appState.timeAxisSpacingConfig.durationGapRatios.quarter,
    durationGapRatio2: appState.timeAxisSpacingConfig.durationGapRatios.half,
    durationGapRatioWhole: appState.timeAxisSpacingConfig.durationGapRatios.whole,
    ...spacingConfigHandlers,
    onOpenMusicXmlFilePicker: workspace.openMusicXmlFilePicker,
    onLoadSampleMusicXml: workspace.loadSampleMusicXmlWithCollapseReset,
    onLoadWholeNoteDemo: workspace.loadWholeNoteDemoWithCollapseReset,
    onLoadHalfNoteDemo: workspace.loadHalfNoteDemoWithCollapseReset,
    onExportMusicXmlFile: workspace.exportMusicXmlFile,
    onOpenOsmdPreview: editorUi.openOsmdPreview,
    onOpenBeamGroupingTool: editorUi.openBeamGroupingTool,
    isNotationPaletteOpen: appState.isNotationPaletteOpen,
    onToggleNotationPalette: editorUi.toggleNotationPalette,
    onCloseNotationPalette: editorUi.closeNotationPalette,
    notationPaletteSelection: appState.notationPaletteSelection,
    notationPaletteLastAction: appState.notationPaletteLastAction,
    notationPaletteActiveItemIdsOverride: editorUi.derivedNotationPaletteDisplay?.activeItemIds ?? null,
    notationPaletteSummaryOverride: editorUi.derivedNotationPaletteDisplay?.summary ?? null,
    onNotationPaletteSelectionChange: editorUi.onNotationPaletteSelectionChange,
    onOpenDirectOsmdFilePicker: editorUi.openDirectOsmdFilePicker,
    onImportMusicXmlFromTextarea: workspace.importMusicXmlFromTextareaWithCollapseReset,
    midiSupported: editorUi.midiSupported,
    midiPermissionState: editorUi.midiPermissionState,
    midiInputOptions: editorUi.midiInputOptions,
    selectedMidiInputId: editorUi.selectedMidiInputId,
    onSelectedMidiInputIdChange: editorUi.setSelectedMidiInputId,
    fileInputRef: editorRefs.fileInputRef,
    osmdDirectFileInputRef: editorUi.osmdDirectFileInputRef,
    onMusicXmlFileChange: workspace.onMusicXmlFileChangeWithCollapseReset,
    onOsmdDirectFileChange: editorUi.onOsmdDirectFileChange,
    importFeedback: appState.importFeedback,
    rhythmPreset: appState.rhythmPreset,
    activeBuiltInDemo: appState.activeBuiltInDemo,
    onApplyRhythmPreset: workspace.applyRhythmPresetWithCollapseReset,
  }), [
    appState.activeBuiltInDemo,
    appState.autoScaleEnabled,
    appState.importFeedback,
    appState.isNotationPaletteOpen,
    appState.isPlaying,
    appState.notationPaletteLastAction,
    appState.notationPaletteSelection,
    appState.pageHorizontalPaddingPx,
    appState.playheadFollowEnabled,
    appState.rhythmPreset,
    appState.staffInterGapPx,
    appState.showChordDegreeEnabled,
    appState.showChordMarkerBackgroundEnabled,
    appState.showInScoreMeasureNumbers,
    appState.showNoteHeadJianpuEnabled,
    appState.timeAxisSpacingConfig,
    appState.setAutoScaleEnabled,
    appState.setCanvasHeightPercent,
    appState.setManualScalePercent,
    appState.setPlayheadFollowEnabled,
    appState.setShowChordDegreeEnabled,
    appState.setShowChordMarkerBackgroundEnabled,
    appState.setStaffInterGapPx,
    appState.setShowInScoreMeasureNumbers,
    appState.setShowNoteHeadJianpuEnabled,
    editorRefs.fileInputRef,
    editorUi.closeNotationPalette,
    editorUi.derivedNotationPaletteDisplay,
    editorUi.midiInputOptions,
    editorUi.midiPermissionState,
    editorUi.midiSupported,
    editorUi.onNotationPaletteSelectionChange,
    editorUi.onOsmdDirectFileChange,
    editorUi.openBeamGroupingTool,
    editorUi.openDirectOsmdFilePicker,
    editorUi.openOsmdPreview,
    editorUi.osmdDirectFileInputRef,
    editorUi.selectedMidiInputId,
    editorUi.setSelectedMidiInputId,
    editorUi.toggleNotationPalette,
    layout.autoScalePercent,
    layout.safeCanvasHeightPercent,
    layout.safeChordMarkerPaddingPx,
    layout.safeChordMarkerUiScalePercent,
    layout.safeManualScalePercent,
    playback.stopActivePlaybackSession,
    spacingConfigHandlers,
    workspace.applyRhythmPresetWithCollapseReset,
    workspace.exportMusicXmlFile,
    workspace.importMusicXmlFromTextareaWithCollapseReset,
    workspace.loadHalfNoteDemoWithCollapseReset,
    workspace.loadSampleMusicXmlWithCollapseReset,
    workspace.loadWholeNoteDemoWithCollapseReset,
    workspace.onMusicXmlFileChangeWithCollapseReset,
    workspace.openMusicXmlFilePicker,
    workspace.playScore,
    workspace.resetScoreWithCollapseReset,
  ])
}
