import { ScoreDisplayControls } from './scoreControls/ScoreDisplayControls'
import { ScoreOsmdPreviewControls } from './scoreControls/ScoreOsmdPreviewControls'
import { ScorePlaybackControls } from './scoreControls/ScorePlaybackControls'
import { ScoreSpacingControls } from './scoreControls/ScoreSpacingControls'
import type { ScoreControlsProps } from './scoreControls/types'

export function ScoreControls(props: ScoreControlsProps) {
  const {
    isPlaying,
    onPlayScore,
    onStopScore,
    onReset,
    playheadFollowEnabled,
    onTogglePlayheadFollow,
    showChordDegreeEnabled,
    onToggleChordDegreeDisplay,
    showChordMarkerBackgroundEnabled,
    onToggleChordMarkerBackgroundDisplay,
    staffInterGapPx,
    onStaffInterGapPxChange,
    showInScoreMeasureNumbers,
    onToggleInScoreMeasureNumbers,
    showNoteHeadJianpuEnabled,
    onToggleNoteHeadJianpuDisplay,
    onLoadWholeNoteDemo,
    onLoadHalfNoteDemo,
    activeBuiltInDemo,
    rhythmPreset,
    onApplyRhythmPreset,
    autoScaleEnabled,
    autoScalePercent,
    onToggleAutoScale,
    manualScalePercent,
    onManualScalePercentChange,
    canvasHeightPercent,
    onCanvasHeightPercentChange,
    pageHorizontalPaddingPx,
    chordMarkerUiScalePercent,
    chordMarkerPaddingPx,
    baseMinGap32Px,
    leadingBarlineGapPx,
    secondChordSafeGapPx,
    durationGapRatio32,
    durationGapRatio16,
    durationGapRatio8,
    durationGapRatio4,
    durationGapRatio2,
    durationGapRatioWhole,
    onPageHorizontalPaddingPxChange,
    onChordMarkerUiScalePercentChange,
    onChordMarkerPaddingPxChange,
    onBaseMinGap32PxChange,
    onLeadingBarlineGapPxChange,
    onSecondChordSafeGapPxChange,
    onDurationGapRatio32Change,
    onDurationGapRatio16Change,
    onDurationGapRatio8Change,
    onDurationGapRatio4Change,
    onDurationGapRatio2Change,
    onDurationGapRatioWholeChange,
    onResetSpacingConfig,
    onOpenMusicXmlFilePicker,
    onOpenDirectOsmdFilePicker,
    onLoadSampleMusicXml,
    onExportMusicXmlFile,
    onOpenOsmdPreview,
    onOpenBeamGroupingTool,
    canOpenPedalModal,
    onOpenPedalModal,
    isNotationPaletteOpen,
    onToggleNotationPalette,
    onCloseNotationPalette,
    notationPaletteSelection,
    notationPaletteLastAction,
    notationPaletteActiveItemIdsOverride,
    notationPaletteSummaryOverride,
    onNotationPaletteSelectionChange,
    onImportMusicXmlFromTextarea,
    midiSupported,
    midiPermissionState,
    midiInputOptions,
    selectedMidiInputId,
    onSelectedMidiInputIdChange,
    fileInputRef,
    osmdDirectFileInputRef,
    onMusicXmlFileChange,
    onOsmdDirectFileChange,
    importFeedback,
  } = props

  return (
    <ScorePlaybackControls
      isPlaying={isPlaying}
      onPlayScore={onPlayScore}
      onStopScore={onStopScore}
      onReset={onReset}
      playheadFollowEnabled={playheadFollowEnabled}
      onTogglePlayheadFollow={onTogglePlayheadFollow}
      showChordDegreeEnabled={showChordDegreeEnabled}
      onToggleChordDegreeDisplay={onToggleChordDegreeDisplay}
      showChordMarkerBackgroundEnabled={showChordMarkerBackgroundEnabled}
      onToggleChordMarkerBackgroundDisplay={onToggleChordMarkerBackgroundDisplay}
      showInScoreMeasureNumbers={showInScoreMeasureNumbers}
      onToggleInScoreMeasureNumbers={onToggleInScoreMeasureNumbers}
      showNoteHeadJianpuEnabled={showNoteHeadJianpuEnabled}
      onToggleNoteHeadJianpuDisplay={onToggleNoteHeadJianpuDisplay}
      autoScaleEnabled={autoScaleEnabled}
      autoScalePercent={autoScalePercent}
      onToggleAutoScale={onToggleAutoScale}
      activeBuiltInDemo={activeBuiltInDemo}
      onLoadWholeNoteDemo={onLoadWholeNoteDemo}
      onLoadHalfNoteDemo={onLoadHalfNoteDemo}
      rhythmPreset={rhythmPreset}
      onApplyRhythmPreset={onApplyRhythmPreset}
    >
      <ScoreDisplayControls
        autoScaleEnabled={autoScaleEnabled}
        manualScalePercent={manualScalePercent}
        onManualScalePercentChange={onManualScalePercentChange}
        canvasHeightPercent={canvasHeightPercent}
        onCanvasHeightPercentChange={onCanvasHeightPercentChange}
      />
      <ScoreSpacingControls
        pageHorizontalPaddingPx={pageHorizontalPaddingPx}
        chordMarkerUiScalePercent={chordMarkerUiScalePercent}
        chordMarkerPaddingPx={chordMarkerPaddingPx}
        staffInterGapPx={staffInterGapPx}
        baseMinGap32Px={baseMinGap32Px}
        leadingBarlineGapPx={leadingBarlineGapPx}
        secondChordSafeGapPx={secondChordSafeGapPx}
        durationGapRatio32={durationGapRatio32}
        durationGapRatio16={durationGapRatio16}
        durationGapRatio8={durationGapRatio8}
        durationGapRatio4={durationGapRatio4}
        durationGapRatio2={durationGapRatio2}
        durationGapRatioWhole={durationGapRatioWhole}
        onPageHorizontalPaddingPxChange={onPageHorizontalPaddingPxChange}
        onChordMarkerUiScalePercentChange={onChordMarkerUiScalePercentChange}
        onChordMarkerPaddingPxChange={onChordMarkerPaddingPxChange}
        onStaffInterGapPxChange={onStaffInterGapPxChange}
        onBaseMinGap32PxChange={onBaseMinGap32PxChange}
        onLeadingBarlineGapPxChange={onLeadingBarlineGapPxChange}
        onSecondChordSafeGapPxChange={onSecondChordSafeGapPxChange}
        onDurationGapRatio32Change={onDurationGapRatio32Change}
        onDurationGapRatio16Change={onDurationGapRatio16Change}
        onDurationGapRatio8Change={onDurationGapRatio8Change}
        onDurationGapRatio4Change={onDurationGapRatio4Change}
        onDurationGapRatio2Change={onDurationGapRatio2Change}
        onDurationGapRatioWholeChange={onDurationGapRatioWholeChange}
        onResetSpacingConfig={onResetSpacingConfig}
      />
      <ScoreOsmdPreviewControls
        onOpenMusicXmlFilePicker={onOpenMusicXmlFilePicker}
        onOpenDirectOsmdFilePicker={onOpenDirectOsmdFilePicker}
        onLoadSampleMusicXml={onLoadSampleMusicXml}
        onExportMusicXmlFile={onExportMusicXmlFile}
        onOpenOsmdPreview={onOpenOsmdPreview}
        onOpenBeamGroupingTool={onOpenBeamGroupingTool}
        canOpenPedalModal={canOpenPedalModal}
        onOpenPedalModal={onOpenPedalModal}
        isNotationPaletteOpen={isNotationPaletteOpen}
        onToggleNotationPalette={onToggleNotationPalette}
        onCloseNotationPalette={onCloseNotationPalette}
        notationPaletteSelection={notationPaletteSelection}
        notationPaletteLastAction={notationPaletteLastAction}
        notationPaletteActiveItemIdsOverride={notationPaletteActiveItemIdsOverride}
        notationPaletteSummaryOverride={notationPaletteSummaryOverride}
        onNotationPaletteSelectionChange={onNotationPaletteSelectionChange}
        onImportMusicXmlFromTextarea={onImportMusicXmlFromTextarea}
        midiSupported={midiSupported}
        midiPermissionState={midiPermissionState}
        midiInputOptions={midiInputOptions}
        selectedMidiInputId={selectedMidiInputId}
        onSelectedMidiInputIdChange={onSelectedMidiInputIdChange}
        fileInputRef={fileInputRef}
        osmdDirectFileInputRef={osmdDirectFileInputRef}
        onMusicXmlFileChange={onMusicXmlFileChange}
        onOsmdDirectFileChange={onOsmdDirectFileChange}
        importFeedback={importFeedback}
      />
    </ScorePlaybackControls>
  )
}
